### ISSUE TITLE
storybook: unknown property

### ISSUE THREAD

**Issue by zkrzyzanowski** [percy/percy-storybook#731]
## The problem
After upgrading to storybook v7 and trying to run snapshots we get the following error:

```
pnpm percy config:validate
[percy] Found config file: .percy.yml
[percy] Invalid config:
[percy] - storybook: unknown property
```

```yaml
version: 2
storybook:
  args: {}
  globals: {}
  queryParams: {}
  waitForTimeout: 10000
  waitForSelector: ''
  additionalSnapshots: []
  include:
    [
      'percy - all fiber components',
      'percy webcomponents - all fiber components',
    ]
  exclude: []

```

tried removing `node_modules` and reinstalling, this happens locally and in our CI environment

## Environment

- Node version: 16.17
- `@percy/cli` version: 1.23.0
- Version of Percy SDK you’re using: 
- If needed, a build or snapshot ID:
- OS version: macOS/linux
- Type of shell command-line [interface]: bash

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Debug logs

If you are reporting a bug, _always_ include logs! [Give the "Debugging SDKs"
document a quick read for how to gather logs](https://docs.percy.io/docs/debugging-sdks#debugging-sdks)

Please do not trim or edit these logs, often times there are hints in the full
logs that help debug what is going on.

## Code to reproduce issue

Given the nature of testing/environment bugs, it’s best to try and isolate the
issue in a reproducible repo. This will make it much easier for us to diagnose
and fix.
